### ISSUE TITLE
Не работает в мобильном клиенте

### ISSUE THREAD

**Issue by vkostyanetsky** [pallid/paint-to-onec#1]
Не удается завести обработку в мобильном клиенте (платформа 8.3.17.1989, мобильная платформа 8.3.16.130). Форма открывается, JS отрабатывает (проверял алертом), но на попытки что-то нарисовать на канве никакой реакции нет.

**Comment by vkostyanetsky** [comment]
В коде вижу функции drawmove() и touchmove(), к которым нет вызова — возможно, их нужно куда-то подключить?

**Comment by vkostyanetsky** [comment]
В общем, в onload() не сделано подключение touchmove():

`canvas.ontouchmove = touchmove;`

**Comment by pallid** [comment]
> В общем, в onload() не сделано подключение touchmove():
> 
> `canvas.ontouchmove = touchmove;`

Здравствуй!!!

А можно тогда RP с исправлением?

да, в [комментарии к статье](http://forum.infostart.ru/forum9/topic170940/message2515877/#message2515877) как раз было описание как использовать в мобильном клиенте

Не могу проверить на мобильном, по этому в этой части могут быть проблемы
